import os

print('Installing necessary packages...')
os.system('pip install zenodo_get')
print('Done')
print('Downloading AlphaMissense Data...')
os.system('zenodo_get 10.5281/zenodo.8360242 -o AlphaMissense_Data')
print('Done')
print('Unziping files...')
os.system('gunzip -d AlphaMissense_hg19.tsv.gz')
print('AlphaMissense_hg19.tsv unziped')
os.system('gunzip -d AlphaMissense_hg38.tsv.gz')
print('AlphaMissense_hg38.tsv unziped')
os.system('gunzip -d AlphaMissense_gene_hg19.tsv.gz')
print('AlphaMissense_gene_hg19.tsv unziped')
os.system('gunzip -d AlphaMissense_gene_hg38.tsv.gz')
print('AlphaMissense_gene_hg38.tsv unziped')
os.system('gunzip -d AlphaMissense_aa_substitutions.tsv.gz')
print('AlphaMissense_aa_substitutions.tsv unziped')
os.system('gunzip -d AlphaMissense_isoforms_hg38.tsv.gz')
print('AlphaMissense_isoforms_hg38.tsv unziped')
os.system('gunzip -d AlphaMissense_isoforms_aa_substitutions.tsv.gz')
print('AlphaMissense_isoforms_aa_substitutions.tsv unziped')
print('AlphaMissense Extractor ready!')
